# Introduction

De acordo com @munafo2017, a pesquisa científica atual enfrenta vários desafios. Problemas como o pequeno tamanho da amostra, pequenos tamanhos de efeito, p-hacking e HARKing (viés positivo de publicação), conflitos de interesse e a competição entre cientistas que trabalham isoladamente sem combinar seus esforços, têm sido apontados como catalizadores do que se convencionou chamar de “crise de reprodutibilidade” na ciência [@baker2016; @munafo2017].

Pesquisas apontam que mais de 70% de pesquisadores que tentaram, falharam em reproduzir os experimentos de outros cientistas, e mais da metade falhou em reproduzir seus próprios experimentos (Baker, 2016), com estimativa de que 85% dos esforços de pesquisas estejam sendo desperdiçados [@munafo2017], gerando custos econômicos bilionários [@freedman2015]. A despeito daqueles que advogam que não existe essa tal “crise de reprodutibilidade” [@bernard2023; @fanelli2018; @protzko2023], a grande maioria da comunidade científica concorda com sua existência e defende a melhoria da transparência, reprodutibilidade e eficiência na ciência (Baker, 2016).

Nesse contexto, o movimento da Ciência Aberta (CA) tem ganhado notoriedade e mudado a percepção sobre o cenário científico global [@cruwell2019]. Ele busca tornar o conhecimento científico mais acessível, transparente e colaborativo. Se apresenta como uma coleção de práticas de democratização do conhecimento e ruptura com o formato único de divulgação do conhecimento científico [@cruwell2019; @heinz2024; @munafo2017]. Ele surge do embate entre aqueles que buscam compartilhar o conhecimento e aqueles que defendem mecanismos de apropriação privada para a produção científica [@heinz2024].

A CA é um termo múltiplo e genérico [@vicente-saez2018], que representa diversas interpretações, e é considerada um novo modelo de divulgação e produção de resultados científicos por meio do acesso livre e irrestrito ao conhecimento [@heinz2024]. A CA não é apenas um conceito, mas uma prática multifacetada que influencia o ciclo de vida da pesquisa, desde a concepção até a disseminação dos resultados [@silva2019]. 
Existem pelo menos cinco escolas de pensamento dentro da CA. Estas escolas abrangem desde a arquitetura tecnológica necessária para suportar a ciência até a inclusão do público geral na criação de conhecimento, passando pela medição do impacto alternativo, acesso ao conhecimento como um direito humano, e a pesquisa colaborativa como inovação aberta [@silva2019]. A taxonomia proposta pela FOSTER (Facilitate Open Science Training for Eurpean Research)(https://www.fosteropenscience.eu/foster-taxonomy/open-workflow-tools), e sua releitura revisada e ampliada para o contexto latino americano por Silveira et al. (2023), tendo em vista as recomendações da UNESCO (2021), nos dá uma dimensão da complexidade do assunto (vide ilustração em: https://doi.org/10.5281/zenodo.7836884).
Existem vários argumentos que sustentam a importância da CA [@heinz2024]. Primeiramente, a CA pode trazer benefícios sociais significativos, pois contribui para o avanço do conhecimento, a inovação, a educação, a transparência e a participação cidadã. Além disso, a CA pode trazer benefícios científicos ao aumentar a qualidade, a reprodutibilidade, a eficiência e o impacto da pesquisa científica. Ela também facilita a colaboração, a comunicação e a interdisciplinaridade entre os pesquisadores. Por fim, a CA pode trazer benefícios éticos ao promover a integridade, a responsabilidade, a equidade e a diversidade na ciência, além de respeitar os direitos dos autores, dos participantes e da sociedade como um todo. 
Esses argumentos são fundamentais para legitimar a CA e destacar sua importância no mundo atual [@heinz2024], principalmente, como potencial transformador para reduzir desigualdades existentes em tecnologias de informação e comunicação – reduzir exclusões digitais, tecnológicas e de conhecimento –, e acelerar o progresso rumo à implementação da Agenda 2030 e realização dos Objetivos de Desenvolvimento Sustentável [@unesco2021].
O movimento da CA no Brasil está em uma fase transitória [@rezende2020] – ainda consolidando o acesso aberto – com o governo desempenhando um papel crucial nesse processo. O Brasil tem ganhado destaque por sua abordagem única na implementação da CA. Esta abordagem é moldada por marcos regulatórios que se estendem desde o governo até as instituições e agências de financiamento. Os regulamentos brasileiros, particularmente aqueles que promovem a abertura de dados governamentais, têm um impacto direto na prática científica. Eles incentivam a transparência e facilitam o acesso a dados científicos originados de instituições públicas [@rezende2020].
A trajetória brasileira rumo à CA inicia com a abertura de dados na esfera governamental entre 2009 e 2016, evoluindo para a criação de um grupo de trabalho em 2017 pelo Ministério da Ciência, Tecnologia, Inovações e Comunicações (MCTIC) para desenvolver uma política nacional para a CA. Este esforço concentrou ênfase no reconhecimento dos dados de pesquisa como ativos de desenvolvimento científico, econômico e social, buscando facilitar seu acesso, compartilhamento e reutilização [@rezende2020].
Talvez por esse motivo, as políticas institucionais brasileiras revelam um cenário ainda muito influenciado pela "via verde" do movimento de acesso aberto, caracterizado pelo depósito de dados em repositórios digitais abertos, e que o comprometimento efetivo do Brasil com a CA ainda é incipiente. As regulamentações atuais favorecem principalmente o acesso aberto, sem abordar de maneira abrangente outros aspectos da CA [@rezende2020]. O Brasil é um dos líderes mundiais no fornecimento de acesso universal às suas pesquisas e estudos [@neto2016], com crescimento estável de sua produção científica disponível em acesso aberto, principalmente, as áreas de Agricultura e Ciência & Tecnologia [@caballero-rivero2019].
Em termos de pesquisa acadêmica sobre o tema no Brasil, os estudos são precoces e concentrados na área de Ciência da Informação [@albano2023]. A despeito da maturidade da CA no Brasil, a importância do tema – materializada na quantidade de produção acadêmica – tem aumentado vertiginosamente [@albano2023], e a dispersão de autores e respectivas instituições que publicam sobre o assunto, parece ser a situação predominante.
Apesar de importantes atores nacionais, tais como CAPES, CNPq e Scielo, defenderem o crescimento de iniciativas de CA [@mendes-da-silva2023], o assunto no Brasil parece estar circunscrito em iniciativas de importantes periódicos nacionais sobre dados aberto, capitaneados pelas orientações da Scielo. Não foi encontrada nenhuma pesquisa empírica, sobre a prática da CA no Brasil.
Por prática de CA entende-se a perspectiva micro da CA, relacionadas com as terminologias e conhecimento em torno do fluxo de trabalho do gerador de conhecimento científico aberto (vide ilustração em: https://doi.org/10.5281/zenodo.10835001), ou seja, o cientista em gestão que se propõe tornar sua pesquisa transparente, reprodutível e replicável. Exclui-se a perspectiva macro, relacionadas com as ramificações conceituais da CA concernentes às políticas públicas, infraestrutura, envolvimento aberto de atores sociais e diálogo aberto com outros sistemas de conhecimento (vide ilustração em: https://doi.org/10.5281/zenodo.10835001). Essa última perspectiva está fora do escopo do projeto, que se concentra em algumas das dimensões da perspectiva micro, particularmente, as ferramentas disponíveis para compilação dos produtos científicos que integram a publicação científica [@unesco2021].
Apesar de uma verossímil expectativa desabonadora, tendo em vista a contexto da CA no Brasil, o diagnóstico da situação da prática da CA se mostra importante, per si, pois: 1) ajuda a compreender a natureza exata do problema, suas causas, efeitos e riscos; 2) auxilia a alocação eficiente de recursos pelos atores envolvidos (e.g., os programas de pós-graduação podem direcionar os recursos para onde eles são mais necessários e onde terão o maior impacto; 3) orienta indicadores de desempenho e metas realistas, o que facilita a avaliação do progresso e a eficácia das ações tomadas; 4) permite que os atores envolvidos aprendam com os problemas enfrentados, adaptando-se e melhorando suas estratégias e processos para o futuro; e 5) torna possível desenvolver soluções ou intervenções que sejam diretamente direcionadas ao problema em questão, aumentando as chances de sucesso.
Sobre esse último ponto, até para aqueles que não reconhecem a “crise de reprodutibilidade” na ciência [@bernard2023], a comunidade científica e atores importantes do cenário advogam que a solução inclui educar os estudantes e pesquisadores desde cedo em todas as questões da CA (Baker et al., 2023; Bezjak et al., 2018; Chopik et al., 2018; Crüwell et al., 2019; Dogucu & Çetinkaya-Rundel, 2022; Janz, 2015; McAleer et al., 2022; Munafò et al., 2017; Toelch & Ostwald, 2018). A referida crise não deriva de má conduta científica, mas principalmente da confusão entre replicar conclusões, replicar resultados, falta de educação em estatística, lógica científica, método científico, alfabetização de dados, etc. Para combater essas questões é necessário investir em educação e disseminação de boas práticas de investigação para uma mudança de cultura (Baker et al., 2023; Bezjak et al., 2018; Chopik et al., 2018; Crüwell et al., 2019; Dogucu & Çetinkaya-Rundel, 2022; Heinz & Miranda, 2024; Janz, 2015; McAleer et al., 2022; Munafò et al., 2017; Toelch & Ostwald, 2018).

Investir em recursos humanos, treinamento, educação, alfabetização digital, capacitação sistemática e contínua, e fomentar uma cultura científica de CA, têm sido apresentadas como algumas das principais medidas simultâneas para superar o cenário atual [@crrs2019; @eu2017; @unesco2021].  
A proposta do presente projeto de pesquisa pode contribuir para a literatura da CA no Brasil, pois pretende perseguir dois objetivos concomitantes: 1) diagnosticar sua prática junto aos pesquisadores brasileiros; e 2) promover o desenvolvimento de uma intervenção educacional sobre a prática (workflow) e principais ferramentas para compilação dos produtos científicos que integram uma publicação científica aberta.
Sobre o primeiro objetivo, os detalhes serão apresentados num pré-registro [@vantveer2016] que disponibilizaremos após a aprovação do projeto, seguindo as boas práticas de CA [@gilroy2019; @kathawalla2021; @klein2018], no entanto, em termos de delineamento pode-se adiantar que a partir da população-alvo, faremos a tradução e adaptação transcultural [@behr2016] do instrumento de medida de Ferguson et al. (2023), que pelas nossas pesquisas preliminares, se mostrou a pesquisa mais ampla e confiável sobre atitudes, usabilidade e percepção sobre as práticas de CA  junto a pesquisadores. Em português não existe nenhum instrumento de medida válido e confiável sobre esses construtos, e esse objetivo per si, pode ser considerado um produto científico.
Em posse do instrumento de medida válido e confiável, seguindo as melhores práticas da literatura psicométrica [@bandalos2018; @cohen2022; @furr2021; @rogers2024; @rogers2022; @urbina2014] e diretrizes da pesquisa original [@ferguson2023] para sua replicação, em outra amostra da população-alvo, diagnosticaremos o panorama geral da prática de CA no Brasil.
Essa segunda amostra será coletada em dois momentos: i) antes da intervenção (pré-teste) e ii) depois da intervenção (pós-teste). Coletaremos informações de indivíduos que realizarão (grupo experimental) e não realização (grupo controle) o treinamento em práticas de CA (tratamento/intervenção). Os participantes serão convidados aleatoriamente – via e-mail e comunicação durante a intervenção para preenchimento de um questionário on-line – para cada um dos grupos. Não teremos a pretensão de escapar do viés de autoseleção e abandono, devido a característica do delineamento.
A amostra que buscará estabelecer uma linha de base (pré-teste) para o treinamento, pode ser utilizada para reflexões sobre o panorama geral da prática de CA no Brasil. No entanto, com a implementação da intervenção e posterior aplicação do pós-teste, poderemos comparar os resultados dentro de cada grupo e medida repetida para avaliar a eficácia do treinamento no quase-experimento. 
Utilizaremos as técnicas estatísticas adequadas para a design metodológico da pesquisa, circunscritas no arcabouço da Modelagem de Equações Estruturais [@hair2019book; @hoyle2023; @kline2023], e seguiremos de perto algumas propostas de workflow para a reprodutibilidade, replicabilidade e transparência da pesquisas [@mang2023; @peikert2021; @peikert2021a; @vanlissa2021], conforme preconizadas nas boas práticas de CA [@gilroy2019; @kathawalla2021; @klein2018].
Diferente do primeiro objetivo, que no presente projeto foi apenas esboçado, o segundo objetivo, quando do começo do projeto, espera-se que esteja com escopo concluído nos moldes recomendados pela literatura de CA [@dogucu2022]. Isso porque o conteúdo do curso faz parte do dia a dia dos proponentes desse projeto. As ferramentas que serão ministradas no curso (OSF, Zotero, Git/Github, Zenodo, RStudio, Quarto, Docker, etc.) fazem parte do workflow de trabalho dos proponentes, e o curso, está sendo concebido enquanto projeto de extensão universitária (https://phdpablo.github.io/curso-open-science/), e será ministrado pelo menos uma vez como piloto no ano corrente.
Cremos que adiantar esse piloto nos ajudará i) avaliar se a intervenção pode ser implementada como planejado no contexto real; ii) identificar e corrigir quaisquer problemas ou falhas na concepção da intervenção antes de realizar o estudo; iii) ajustar os materiais, recursos, métodos e procedimentos operacionais do treinamento para melhorar a eficácia e a eficiência; iv) familiarizar com o processo e resolver quaisquer dificuldades operacionais; v) garantir que todos os envolvidos compreendam e sigam o protocolo de pesquisa corretamente [@janghorban2014], reduzindo a variabilidade na implementação; v) identificar potenciais problemas éticos; e vi) definir expectativas realistas sobre os resultados e o impacto da intervenção, tanto para os pesquisadores quanto para os participantes [@kezar2000; @thabane2010].
Esse quase-experimento como uma pesquisa-ação, em um contexto universitário, integra de forma profícua as atividades de ensino, pesquisa e extensão universitária [@estevescampos2020], promovendo a indissociabilidade, interdisciplinaridade, multidimensionalidade, integração e articulação dessa tríade, quase sempre inexistente em grande parte dos projetos de pesquisa nas universidade brasileiras [@farias2010], porém de suma importância [@goncalves2015]. 
Nesse sentido, esse projeto de pesquisa se associa à um projeto de ensino por proporcionar uma experiência de aprendizagem integrada para os envolvidos na academia, desenvolvendo habilidades e competências essenciais [@moita2009]. Como projeto de extensão, ele transcende os limites da universidade, aplicando o conhecimento gerado para beneficiar a comunidade mais ampla e promover mudanças sociais positivas [@rays2012], principalmente, através da comunicação científica [@targino2000].

